### ISSUE TITLE
`require` is not defined because, apparently the most recent versions of Browserify do not expose require to the global scope

### ISSUE THREAD

**Issue by barbu110** [hhvm/xhp-js#1]
The example provided in the `example` repository will not work with the latest version of Browserify, because seems like Browserify does not expose the `require()` method the global scope. 

What can be done for using the modules with the magical `require()`?

**Comment by fredemmott** [comment]
Sorry, was on leave - I'll look into how to fix this. Until then, the non-module form should still work.

**Comment by fredemmott** [comment]
In my testing, require() is still provided by the latest version, 13.1.0; are you using 'browserify -r YourModuleHere' ?
